### ISSUE TITLE
add GitHub Action to check website code

### ISSUE THREAD

**Issue by ana** [avocado-framework/avocado-framework.github.io#20]
We should add a github action to check the website HTML code when a pull request is send and/or accepted.

**Comment by clebergnu** [comment]
To avoid connections into the server, I'd added a crontab entry that will sync the content every hour.  I guess that's good enough and we can close this.

**Comment by clebergnu** [comment]
@ana let me know if you consider this OK.  If so, please close this issue.

**Comment by ana** [comment]
@clebergnu Thanks for taking care of that! The idea of this issue is also to add some HTML Checking when we people submit changes. I'll edit the issue to make it more clear.
