### ISSUE TITLE
update webserver with fresh data

### ISSUE THREAD

**Issue by beraldoleal** [avocado-framework/avocado-framework.github.io#21]
As pointed here https://github.com/avocado-framework/avocado-framework.github.io/pull/18#issuecomment-872975914, we need to update the website.

We have an issue (#20) to automate this (thanks @ana), but in meanwhile we need a sync. AFAICT, @clebergnu  has access to that server.

**Comment by clebergnu** [comment]
It's now up to date.

To avoid connections into the server, I'd added a crontab entry that will sync the content every hour.  I guess that's good enough and we can close this.
